---
- hosts: server
  tasks:
  - name: Install Docker
    become: yes
    apt:
      name: docker.io
      state: present
  - name: Start service docker, if not started
    become: yes
    service:
      name: docker
      state: started
      enabled: yes
  - name: Install Pip
    become: yes
    apt:
      name: python3-pip
      state: present
  - name: install py docker
    pip:
      name: docker
  - name: install py docker compose
    pip:
      name: docker-compose
  - name: Start services
    community.docker.docker_compose:
      project_name: hofc
      pull: yes
      definition:
        version: '3'
        services:
          reverse-proxy:
            image: traefik:v2.4
            # Enables the web UI and tells Traefik to listen to docker
            command: --providers.docker
            ports:
              - "8443:443"
            volumes:
              # So that Traefik can listen to the Docker events
              - /var/run/docker.sock:/var/run/docker.sock