---
- hosts: server
  tasks:
  - name: Install Docker
    become: yes
    apt:
      name: docker.io
      state: present
  - name: Start service docker, if not started
    become: yes
    service:
      name: docker
      state: started
      enabled: yes
  - name: Install Pip
    become: yes
    apt:
      name: python3-pip
      state: present
  - name: install py docker
    pip:
      name: docker
  - name: install py docker compose
    pip:
      name: docker-compose
  - name: Log into private registry and force re-authorization
    community.docker.docker_login:
      registry_url: docker.pkg.github.com
      username: "{{ lookup('env','REGISTRY_USER') }}"
      password: "{{ lookup('env','REGISTRY_PASS') }}"
      reauthorize: yes
  - name: Start services
    community.docker.docker_compose:
      project_name: hofc
      pull: yes
      definition:
        version: '3'
        services:
          reverse-proxy:
            image: traefik:v2.4
            restart: unless-stopped
            # Enables the web UI and tells Traefik to listen to docker
            command: 
              - "--providers.docker=true"
              - "--providers.docker.exposedbydefault=false"
              - "--entrypoints.web.address=:443"
              - "--api.dashboard=true" 
              - "--api.insecure=true"
            environment:
              TRAEFIK_ENTRYPOINTS_WEB_HTTP_TLS_DOMAINS_0_MAIN: api.maladot.ovh
              TRAEFIK_ENTRYPOINTS_WEB_HTTP_TLS_DOMAINS_0_SANS: "*.api.maladot.ovh"
              TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER: 'false'
              TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_CASERVER: https://acme-staging-v02.api.letsencrypt.org/directory #https://acme-v02.api.letsencrypt.org/directory
              TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_EMAIL: "{{ lookup('env','ACME_EMAIL') }}"
              TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_STORAGE: acme.json
              TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_DNSCHALLENGE_PROVIDER: ovh
              OVH_ENDPOINT: "ovh-eu"
              OVH_APPLICATION_KEY: "{{ lookup('env','OVH_APPLICATION_KEY') }}"
              OVH_APPLICATION_SECRET: "{{ lookup('env','OVH_APPLICATION_SECRET') }}"
              OVH_CONSUMER_KEY: "{{ lookup('env','OVH_CONSUMER_KEY') }}"
            ports:
              - "8443:443"
            volumes:
              # So that Traefik can listen to the Docker events
              - /var/run/docker.sock:/var/run/docker.sock
          fff-system:
            image: docker.pkg.github.com/orome656/fff-system-api/fff-system-api:latest
            restart: unless-stopped
            labels:
              - "traefik.enable=true"
              - "traefik.http.routers.fff-system.rule=Host(`fff-system.api.maladot.ovh`)"
              - "traefik.http.routers.fff-system.entrypoints=web"
              - "traefik.http.services.fff-system.loadbalancer.server.port=5000"
              - "traefik.http.routers.fff-system.tls=true"
              - "traefik.http.routers.fff-system.tls.certresolver=myresolver" 
            environment:
              api_user: "{{ lookup('env','API_USER') }}"
              api_password: "{{ lookup('env','API_PASSWORD') }}"
              fff_client_id: "{{ lookup('env','FFF_CLIENT_ID') }}"
              fff_client_secret: "{{ lookup('env','FFF_CLIENT_SECRET') }}"
              fff_username: "{{ lookup('env','FFF_USERNAME') }}"
              fff_password: "{{ lookup('env','FFF_PASSWORD') }}"
              fff_token_password: "{{ lookup('env','FFF_TOKEN_PASSWORD') }}"
