name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: fff-system-api

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Get private key
        env:
          USERNAME: ${{ secrets.Username }}
          SERVER: ${{ secrets.Server }}
          KEY: ${{ secrets.Key }}
        run: |
          echo "$KEY" > private_key.ppk && chmod 600 private_key.ppk
          mkdir ~/.ssh && touch ~/.ssh/known_hosts
          ssh-keyscan "$SERVER" >> ~/.ssh/known_hosts
          sed -i 's/<server_host>/$SERVER/g' ./ansible/inventory
          sed -i 's/<server_user>/$USERNAME/g' ./ansible/inventory
      - name: run ansible playbook
        env:
          ROOT_PASS: ${{ secrets.Root_pass }}
        run: cd ansible && ansible-playbook -i inventory --become-method=su --extra-vars "ansible_become_pass=$ROOT_PASS"