name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

  repository_dispatch:
    types: [backend_deploy]

env:
  IMAGE_NAME: fff-system-api

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Get private key
        env:
          USERNAME: ${{ secrets.Username }}
          SERVER: ${{ secrets.Server }}
          KEY: ${{ secrets.Key }}
        run: |
          echo "$KEY" > ~/private_key.ppk && chmod 600 ~/private_key.ppk
          mkdir ~/.ssh && touch ~/.ssh/known_hosts
          ssh-keyscan "$SERVER" >> ~/.ssh/known_hosts
          sed -i "s/<server_host>/$SERVER/g" ./ansible/inventory
          sed -i "s/<server_user>/$USERNAME/g" ./ansible/inventory
      - name: run ansible playbook
        env:
          ROOT_PASS: ${{ secrets.Root_pass }}
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
          FFF_CLIENT_ID: ${{ secrets.FFF_CLIENT_ID }}
          FFF_CLIENT_SECRET: ${{ secrets.FFF_CLIENT_SECRET }}
          FFF_USERNAME: ${{ secrets.FFF_USERNAME }}
          FFF_PASSWORD: ${{ secrets.FFF_PASSWORD }}
          FFF_TOKEN_PASSWORD: ${{ secrets.FFF_TOKEN_PASSWORD }}
          API_USER: ${{ secrets.API_USER }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
          OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
          OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
          ACME_EMAIL: ${{ secrets.ACME_EMAIL }}
        run: cd ansible && ansible-playbook -i inventory --become-method=su --extra-vars "ansible_become_pass=$ROOT_PASS" hofc.yml